# installing APT GUI packages
#
# usage:
# ./install-standalone apt-gui-sudo
- shell:
    - command: apt update
      description: Update APT repository index
    - command: apt upgrade -y
      description: Upgrade installed packages
    - command: grep -Ev '^#' $DOTBOT_INSTALL_LIST_PATH/apt-gui | xargs apt install -y
      description: Installing APT GUI packages
    - command: apt autoremove -y
      description: Remove unused packages
