# install astronvim and link config files
#
# usage:
# ./install-standalone astronvim
- shell:
    - command: rm -rf $NVIM_CONFIG_DIR_PATH $NVIM_PACKER_DIR_PATH $NVIM_PACKER_COMPILED_PATH
      description: Remove old Neovim installed plugins
    - command: git clone https://github.com/AstroNvim/AstroNvim $NVIM_CONFIG_DIR_PATH
      description: Get AstroNvim repo
- link:
    $ASTRO_NVIM_CONFIG_DIR_PATH: tools/astronvim
- shell:
    - command: nvim --headless -c 'PackerSync' -c 'autocmd User PackerComplete quitall'
      description: Installing Neovim packages
