# install astronvim and link config files
#
# usage:
# ./install-standalone astronvim
- shell:
    - command: |
        rm -rfv \\
        $NVIM_CONFIG_DIR_PATH \\
        $HOME/.local/share/nvim/lazy \\
        $HOME/.local/share/nvim/lazy-lock.json \\
        $HOME/.cache/nvim
      description: Remove old Neovim installed plugins
    - command: git clone https://github.com/AstroNvim/AstroNvim $NVIM_CONFIG_DIR_PATH
      description: Get AstroNvim repo
- link:
    $ASTRO_NVIM_CONFIG_DIR_PATH: tools/astronvim
- shell:
    - command: nvim --headless -c 'autocmd User LazyDone quitall' -c 'sleep 40' -c 'quitall'
      description: Installing Neovim packages
#     - command: nvim --headless -c 'TSUpdateSync' -c 'sleep 30' -c 'qa'
#       description: Install Nvim-Treesitter language packs
