# enable fedora dnf copr (Cool Other Package Repo)
#
# usage:
# ./install-standalone dnf-copr-sudo
- shell:
    - command: grep -Ev '^#' $DOTBOT_INSTALL_LIST_PATH/dnf-copr | xargs dnf copr enable -y
      description: Enable copr repos
    - command: dnf update -f
