# install fedora gui packages
#
# usage:
# ./install-standalone dnf-gui-sudo
- shell:
    - command: dnf update -y
      description: Updating dnf packages
    - command: grep -Ev '^#' $DOTBOT_INSTALL_LIST_PATH/dnf-gui | xargs dnf install -y
      description: Install dnf gui packages
