# install fedora packages
#
# usage:
# ./install-standalone dnf-sudo
- link:
    /etc/dnf/dnf.conf: tools/dnf/dnf.conf
- shell:
    - command: dnf update -y
      description: Updating dnf packages
    - command: grep -Ev '^#' $DOTBOT_INSTALL_LIST_PATH/dnf | xargs dnf install -y
      description: Install dnf packages
