# install fedora packages
#
# usage:
# ./install-standalone dnf-sudo
- shell:
    - command: dnf update -y
      description: Updating dnf packages
    - command: grep -Ev '^#' meta/install-list/dnf | xargs dnf install -y
      description: Install dnf packages
