# Install docker on debian
# Docker installation instructions obtained from
# https://docs.docker.com/engine/install/debian/
#
# usage:
# ./install-standalone docker-debian-sudo
- shell:
    - command: |
        if [[ -n $(command -v docker) ]]; then
          apt remove -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
          apt autoremove -y

          # stopping service to prevent error when starting the service when installing docker.
          # docker.service is autostarted by docker.socket. Causing error when install docker services
          systemctl stop docker.socket --now
        fi
      description: Remove currently installed docker packages
    - command: rm -rfv /usr/share/keyrings/docker-archive-keyring.gpg /etc/apt/sources.list.d/docker.list
      description: Remove Docker GPG file and remove Apt repository
    - command: apt update
    - command: apt install -y ca-certificates curl gnupg lsb-release
      description: Add packages to allow APT to use repositories over HTTPS
    - command: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      description: Add Docker official GPG key
    - command: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \\
        $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      description: Setting up Docker stable repository
    - command: apt update
    - command: apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
      description: Install Docker engine
