# Cron job used for auto updating dotfiles repo
# it will discard all uncommitted, unstaged and unpushed changes
# 
# usage:
# ./install-standalone dotfiles-cron-sudo
- link:
    /etc/cron.daily/dotfiles-autoupdate: tools/cron/dotfiles-autoupdate
- shell:
    - command: chmod u+x tools/cron/dotfiles-autoupdate
      description: Ensure tools/cron/dotfiles-autoupdate is executable 
