# fixing locale settings
#
# obtained from https://gist.github.com/ChrisTitusTech/f55e2fd0b39b268fed251d12bd91b5e8
#
# usage:
# ./install-standalone fix-locale-sudo
- shell:
    - command: echo "LC_ALL=en_CA.UTF-8" | tee -a /etc/environment
    - command: echo "en_CA.UTF-8 UTF-8" | tee -a /etc/locale.gen
    - command: echo "LANG=en_CA.UTF-8" | tee -a /etc/locale.conf
    - command: locale-gen en_CA.UTF-8
