# install homebrew and homebrew packages
#
# usage:
# ./install-standalone homebrew
- shell:
    - command: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | INTERACTIVE=1 bash
      description: Installing Homebrew
    # brewfile obtained with
    # brew bundle dump --describe --file=meta/install-list/Brewfile --force
    - command: brew bundle --file meta/install-list/Brewfile --verbose --cleanup --no-lock
      description: Installing Homebrew packages
