# installing APT non-gui packages using nala
#
# NOTE: make sure to run dotbot config 'nala.yaml' before running this dotbot config
#
# usage:
# ./install-standalone nala-terminal-sudo
- shell:
    - command: nala update
      description: Update APT repository
    - command: nala upgrade -y
      description: Upgrade APT packages
    - command: grep -Ev '^#' $DOTBOT_INSTALL_LIST_PATH/apt | xargs nala install -y
      description: Installing APT packages
    - command: nala autoremove -y
      description: Remove unused packages
