# setting up neovim configs and installing neovim plugins
#
# usage:
# ./install-standalone neovim-packages
- link:
    $NVIMRC_PATH: tools/neovim/init.lua
    $NVIM_CONFIG_DIR_PATH: tools/neovim/lua/
- shell:
    - command: rm -rf $NVIM_PACKER_DIR_PATH
      description: Removing existing Neovim Packer installation directory
    - command: nvim --noplugin -c 'autocmd User PackerComplete quitall'
      description: Installing Neovim packages
