# setting up neovim configs and installing neovim plugins
#
# usage:
# ./install-standalone neovim-packages
- link:
    ~/.config/nvim/init.lua: tools/neovim/init.lua
    ~/.config/nvim/lua: tools/neovim/lua/
- shell:
    - command: rm -rf  ~/.local/share/nvim/site/pack
      description: Removing existing Neovim Packer installation directory
    - command: nvim --noplugin -c 'autocmd User PackerComplete quitall'
      description: Installing Neovim packages
