# installing precompiled neovim
#
# download precompiled tarball from
# https://github.com/neovim/neovim/releases/tag/stable
#
# usage:
# ./install-standalone neovim-precompiled-sudo
- shell:
    - command: rm -rf /usr/local/bin/nvim /usr/local/lib64/nvim /usr/local/share/nvim/
      description: Remove currently installed Neovim(built from source)
    - command: curl -L --output /tmp/nvim-linux64.tar.gz https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
      description: Get precompiled neovim from Github releases
    - command: tar -xzf /tmp/nvim-linux64.tar.gz -C /tmp/
      description: Extract tarball contents
    - command: cp -vR /tmp/nvim-linux64/bin/ /usr/local/
    - command: cp -vR /tmp/nvim-linux64/lib/nvim/ /usr/local/lib64/
    - command: cp -vR /tmp/nvim-linux64/share/ /usr/local/
    - command: rm -rf /tmp/nvim-linux64/ /tmp/nvim-linux64.tar.gz
      description: Remove tarball and it's extracted contents
