- link:
    ~/.config/nvim/init.lua: tools/neovim/init.lua
    ~/.config/nvim/lua: tools/neovim/lua/
- shell:
    - command: rm -r  ~/.local/share/nvim/site/pack
      description: Removing existing Neovim Packer installation directory
    - command: nvim --noplugin -c 'autocmd User PackerComplete quitall'
      description: Installing Neovim packages
    # install TreeSitter languages
    # extract languages from tools/neovim/lua/config/treesitter.lua
    # put it result in a variable
    # install Treesitter languages using the variable
    #
    # command: sort | uniq : is used for removing duplicate entries
    # command: tr '\\n' ' ' : replace newline into spaces. Putting all languages into oneline so it can be stored in a variable
    - command:
        tslang="$(grep -Eo '(\"\w+\",*?)' tools/neovim/lua/config/treesitter.lua | grep -Eo '\w+' |
        sort | uniq | tr '\\n' ' ')" &&
        echo "installing TreeSitter languages \\n$(echo $tslang | tr ' ' '\\n')" &&
        nvim --headless -c "TSInstallSync $tslang" -c 'qall'
      description: Installing TreeSitter languages
