# installing node version manager and installing global node packages
#
# usage:
# ./install-standalone nvm
- link:
    $NPM_CONFIG_USERCONFIG: tools/npm/.npmrc
- create:
    - ~/.local/share/nvm
- shell:
    - command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | PROFILE=/dev/null zsh
      description: Installing Node version manager
    - command: source $NVM_DIR/nvm.sh && nvm install node
      description: install latest version of NodeJS
    # - load exports from zsh/exports.zsh to be able access nvm
    # - get npm packages from meta/install-list/npm that are NOT commented out (commented with # )
    #   - ignore line starting with #
    # - install NPM packages
    #
    # obtained regex from
    #   https://unix.stackexchange.com/a/174720
    #   https://unix.stackexchange.com/a/60995
    - command: source $NVM_DIR/nvm.sh && grep -Ev '^#' meta/install-list/npm | xargs npm install -g
      description: Installing NPM packages
