# installing Oh-my-zsh
#
# usage:
# ./install-standalone ohmyzsh
- create:
    - $ZSH_CACHE_DIR
- shell:
    - command: rm -rf $OH_MY_ZSH_DIR_PATH
      # - command: chsh -s $(which zsh)
      # stdin: true
      description: Changing default Shell to ZSH
    - command: |
        ZSH="$OH_MY_ZSH_DIR_PATH" \\
        KEEP_ZSHRC=yes \\
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      description: Install Oh-my-zsh
    - command: echo -e "\\n\\033[1;33mReload your terminal to finish Oh-my-zsh installation"
