# install pihole DNS Ad-Blocker
#
# usage:
# ./install-standalone pihole-sudo
- link:
    /etc/pihole/setupVars.conf: tools/pihole/setupVars.conf
    /etc/pihole/adlists.list: tools/pihole/adlists.list
- shell:
    # install without user interaction.
    # needs /etc/pihole/setupVars.conf
    # obtained from https://unix.stackexchange.com/a/423744
    - command: |
        curl  -sSL \\
              --max-time 10 \\
              --retry 5 \\
              --retry-delay 10 \\
              --retry-max-time 40 \\
              https://install.pi-hole.net | bash /dev/stdin --unattended
      description: install PiHole
