# install pyenv and install latest python version
#
# usage:
# ./install-standalone pyenv
- shell:
    - command: |
        if [ -d "$PYENV_DIR_PATH" ]; then
          command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH" ;
          eval "$(pyenv init -)" ;
          pyenv update ;
        fi
      description: Update pyenv if it exists

    - command: |
        if [ ! -d "$PYENV_DIR_PATH" ]; then
          curl https://pyenv.run | bash
        fi
      description: install pyenv if it's not installed

    - command: |
        command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH" ;
        eval "$(pyenv init -)" ;
        pythonVersion=$(pyenv install --list | grep --extended-regexp "^\s*[0-9][0-9.]*[0-9]\s*$" | tail -1)
        pyenv install --skip-existing $pythonVersion
        pyenv global $pythonVersion
      description: install the latest python version
