# installing spacevim configs
#
# usage:
# ./install-standalone spacevim
- shell:
    - command: rm -rf ~/.vim ~/.SpaceVim ~/.SpaceVim.d
      description: Removing existing vim and SpaceVim file/directories
    - command: curl -sLf https://spacevim.org/install.sh | bash -s -- --install vim
      description: Download SpaceVim configs and link to vim
- link:
    ~/.SpaceVim.d/init.toml: tools/spacevim/init.toml
