# setting up tmux config and installing tmux plugins
#
# usage:
# ./install-standalone tmux
- link:
    $TMUX_CONFIG_PATH: tools/tmux/tmux.conf
- shell:
    - command: rm -rf ~/.local/share/tmux/
      description: Remove existing tmux plugins
    - command: tmux -f $TMUX_CONFIG_PATH start-server
      description: Installing tmux plugins...
    - tmux -f $TMUX_CONFIG_PATH new-session -d
    # - sleep 1
    # - $TMUX_PLUGIN_CACHE_PATH/tpm/scripts/install_plugins.sh
    - tmux -f $TMUX_CONFIG_PATH kill-server
