# setting up ufw config for pihole
#
# usage:
# ./install-standalone ufw-pihole-sudo
- shell:
    - command: ufw disable
      description: Turn off ufw
    - command: ufw default allow outgoing
      description: Allow outgoing traffic as default
    - command: ufw default deny incoming
      description: Block incoming traffic as default
    - command: ufw allow 22 comment "SSH"
      description: Allow port 22 for SSH
    - command: ufw allow 80 comment "PiHole WebPortal"
      description: Allow port 80 for PiHole WebPortal
    - command: ufw allow 53 comment "PiHole DNS"
      description: Allow port 53 for PiHole DNS
    - command: echo 'yes' | ufw enable
      description: Turn on ufw
    - command: ufw status verbose
