# installing vscode extensions
#
# usage:
# ./install-standalone vscode-plugins
- shell:
    # - get vscode extensions from meta/install-list/vscode that are NOT commented out (commented with # )
    #   - ignore line starting with #
    # - install VScode packages
    #
    # obtained regex from
    #   https://unix.stackexchange.com/a/174720
    #   https://unix.stackexchange.com/a/60995
    - command: |
        for extension in $(grep -Ev '^#' meta/install-list/vscode)
        do
          code --install-extension $extension
        done
      description: Installing VScode plugins
