# installing vscode in fedora
# obtained from https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions
#
# NOTE: running config as sudo
# usage:
# ./install-standalone vscode-fedora-sudo
- shell:
    # installation steps obtained from https://code.visualstudio.com/docs/setup/linux
    - command: rpm --import https://packages.microsoft.com/keys/microsoft.asc
      description: Adding VScode GPG key to RPM
    - command: tee /etc/yum.repos.d/vscode.repo &> /dev/null << EOF\n
        [code]\n
        name=Visual Studio Code\n
        baseurl=https://packages.microsoft.com/yumrepos/vscode\n
        enabled=1\n
        gpgcheck=1\n
        gpgkey=https://packages.microsoft.com/keys/microsoft.asc\n
        EOF
      description: Adding VScode repo to Fedora package manager
    - command: dnf update -y
      description: Updating Fedora package index
    - command: dnf install -y code
      description: Install VScode
