---

# this file will look for vars
# - dnf_packages
# - dnf_group_packages
#
# make sure to load it in the playbook
#
# installing group packages
# - https://linuxconfig.org/how-to-work-with-dnf-package-groups

- name: "Update dnf config file"
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf
    block: |
      # added for speed
      # obtained from
      # - https://www.youtube.com/watch?v=RrRpXs2pkzg&t=50s
      fastestmirror=True
      max_parallel_downloads=10
      defaultyes=True
      keepcache=True
    prepend_newline: true
    append_newline: true
    create: true
  become: true

  # obtained from
  # - https://rpmfusion.org/Configuration#Command_Line_Setup_using_rpm
  # - https://youtu.be/RrRpXs2pkzg?si=Hnu3EDDgyhoiGar4&t=296
  # - https://serverfault.com/a/1021745
- name: "Enable RPM fusion"
  block:
    # obtained from
    # - https://rpmfusion.org/keys
    # - https://github.com/fabaff/fedora-ansible/blob/4d8d3f7/tasks/rpmfusion.yml#L1-L22
    - name: "Add rpmfustion repo gpg keys"
      ansible.builtin.rpm_key:
        key: "{{ item }}"
        state: present
      with_items:
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
      become: true

    - name: "Enable RPM fusion"
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      become: true

    # allows gui package manager to load packages from the newly added rpm fusion mirrors
    # obtained from
    # - https://rpmfusion.org/Configuration#AppStream_metadata
    # - https://www.youtube.com/watch?v=RrRpXs2pkzg&t=362s
    - name: "Install group package core"
      dnf:
        name: "@core"
        state: present
      become: true

# obtained from
# - https://youtu.be/RrRpXs2pkzg?t=499&si=x9IKb-cs9gapNfaY
- name: "Enable multimedia codecs"
  block:
    # obtained from
    # - https://rpmfusion.org/Howto/Multimedia#Switch_to_full_ffmpeg
    - name: "Switch to full ffmpeg"
      command:
        cmd: "sudo dnf swap ffmpeg-free ffmpeg --allowerasing -y"
      become: true

    # obtained from
    # - https://rpmfusion.org/Howto/Multimedia#Install_additional_codec
    # - https://www.youtube.com/watch?v=RrRpXs2pkzg&t=499s
    - name: "Install/update media codecs"
      shell:
        cmd: |
          dnf install @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y
          dnf update @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y
      become: true

    - name: "Install/update group package sound-and-video"
      shell:
        cmd: |
          dnf install @sound-and-video -y
          dnf update @sound-and-video -y
      become: true

- name: "Update dnf packages"
  dnf:
    update_cache: true
  become: true

- name: "Upgrade installed packages"
  dnf:
    update_only: true
  become: true

- name: "Install dnf packages"
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ dnf_packages }}"
  become: true

- name: "Install dnf group packages"
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ dnf_group_packages }}"
  become: true

- name: "Autoremove dnf packages"
  dnf:
    autoremove: true
  become: true
