---
# install rust
# obtained from
# https://waylonwalker.com/install-rust

- name: "Check if cargo is installed"
  shell:
    cmd: command -v cargo > /dev/null 2>&1
  register: cargo_exists
  ignore_errors: true
  failed_when: false
  changed_when: cargo_exists.rc != 0

- name: "Download Installer"
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"
  when: cargo_exists.rc != 0

- name: "Install rust/cargo"
  command: /tmp/sh.rustup.rs -y
  when: cargo_exists.rc != 0

- name: "Update rust"
  command: rustup update
  when: cargo_exists.rc == 0

- name: "Remove installer"
  file:
    path: /tmp/sh.rustup.rs
    state: absent
  when: cargo_exists.rc != 0
