---
# install rust
# obtained from
# https://waylonwalker.com/install-rust

- name: "Check if cargo is installed"
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: "Download Installer"
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"
  when: cargo_exists is failed

- name: "Install rust/cargo"
  command: /tmp/sh.rustup.rs -y
  when: cargo_exists is failed

- name: "Update rust"
  command: rustup update
  when: cargo_exists

- name: "Remove installer"
  file:
    path: /tmp/sh.rustup.rs
    state: absent
  when: cargo_exists is failed
