-- load plugins config here

require "config.telescope"
require "config.cmp"
require "config.cmp-git"
require "config.lsp"
require "config.treesitter"
require "config.which-key"
require "config.toggleterm"
require "config.bufferline"
require "config.nvim-tree"
require "config.symbols-outline"
require "config.gitsigns"
require "config.comment"
require "config.autopairs"
require "config.alpha"
require "config.project"

require "config.theme"
require "config.indent-blankline"
require "config.colorizer"
require "config.lualine"
