---

# Install Node Version Manager

- name: "Create directory for Node Version Manager on {{ zshenv.NVM_DIR }}"
  file:
    path: "{{ zshenv.NVM_DIR }}"
    state: directory

- name: "Create directory for NPM  on {{ zshenv.NPM_DIR }}"
  file:
    path: "{{ zshenv.NPM_DIR }}"
    state: directory

- name: "Link NPM config file"
  file:
    src: "{{ zshenv.DOTDIR }}/tools/npm/.npmrc"
    dest: "{{ zshenv.NPM_CONFIG_USERCONFIG }}"
    state: link

- name: "Install Node Version Manager"
  shell:
    cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | PROFILE=/dev/null bash

- name: "Install latest NodeJS version"
  shell:
    cmd: "source {{ zshenv.NVM_DIR }}/nvm.sh && nvm install node --default --latest-npm"
    executable: /bin/bash
