#!/usr/bin/env bash

# used for running individual installation scripts located in ./meta/configs/ folder
# usage:
# ./install-standalone nvim
# ./install-standalone tmux
# ./install-standalone zsh
#
# or
# ./install-standalone nvim tmux zsh
#
# NOTE: to run a config in sudo, then add '-sudo' as a suffix of the config to run.
# Ex: ./install-standalone apt-sudo
# check: https://github.com/ecarlson94/dotbot-template#for-installing-single-configurations
#
# ./meta/configs/ folder will contain .yaml files that will be used as config. It
# has the same directives as the default dotbot install-conf.yaml
# check: https://github.com/anishathalye/dotbot#full-example
#
# obtained from https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks#install-standalone
# author ecarlson94

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


cd "${BASE_DIR}"
git submodule update --init --recursive

# load env variables.
# load XDG dotfile locations. https://wiki.archlinux.org/title/XDG_Base_Directory
source tools/zsh/.zshenv

for config in ${@}; do
  # create temporary file
  configFile="$(mktemp)"
  suffix="-sudo"
  echo -e "$(<"${BASE_DIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config%"$suffix"}${CONFIG_SUFFIX}")" > "$configFile"

  cmd=("${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "$configFile")

  # print a line depending on the terminal width
  # https://unix.stackexchange.com/a/425158
  # https://stackoverflow.com/a/17030976/3053548
  printf '%0.s=' $(seq 1 $(stty size | awk '{print $2}'))
  printf '%0.s=' $(seq 1 $(stty size | awk '{print $2}'))
  echo -e "\nConfigure $config\n"

  if [[ $config == *"sudo"* ]]; then
      cmd=(sudo "${cmd[@]}")
  fi

  "${cmd[@]}"
  rm -f "$configFile"
done

cd "${BASE_DIR}"