---

- name: PopOS dotfiles
  hosts: localhost
  connection: local
  # vars_files:
  #   - Pop!_OS.yaml

  pre_tasks:
    - name: Load ENVs
      ansible.builtin.import_tasks: pre_tasks/load-envs.yaml
      tags:
        - always

    - name: "Import var file {{ ansible_distribution }}.yaml"
      ansible.builtin.include_vars:
        file: "vars/{{ ansible_distribution }}.yaml"
      tags:
        - always

  tasks:
    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts
    #   tags:
    #     - always

    - name: Print default_roles
      ansible.builtin.debug:
        var: default_roles
      tags:
        - always

    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) | sort }}"
      tags:
        - always

    - name: Roles to run
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
