---

- name: PopOS dotfiles
  hosts: localhost
  connection: local
  vars_files:
   - Pop!_OS.yaml

  pre_tasks:
    - name: Load ENVs
      ansible.builtin.import_tasks: pre_tasks/load-envs.yaml
      tags:
        - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) | sort }}"
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
