#!/bin/bash
# 
# NOTE: this not to be run by bash.
#       this is ONLY used for reading the file contents.
#       the shebang is used by VScode for syntax highlighting
#       file is read using 'install-profile'
# a list of dotbot config to run
# 
# to omit a config from being run, add # at the beginning of the line

fix-locale-sudo
apt-sudo
git
neofetch
spacevim
nvm
neovim-precompiled-sudo
astronvim
go-packages
rust
rust-packages
tmux
zsh
ohmyzsh
