#!/bin/bash
# 
# NOTE: this not to be run by bash.
#       this is ONLY used for reading the file contents.
#       the shebang is used by VScode for syntax highlighting
#       file is read using 'install-profile'
# a list of dotbot config to run
# 
# to omit a config from being run, add # at the beginning of the line

raspberrypi-configs-sudo
debian-apt-sources-sudo
apt-sudo
raspberrypi-unattended-upgrades-sudo
git
neofetch
tmux
zsh
ohmyzsh
spacevim
nvm
neovim-source-build-sudo
astronvim
pihole-sudo
unbound-sudo
ufw-pihole-sudo
pihole-cron-sudo
fail2ban-sudo
