---

vscode_extensions:
  # - VladimirMikulic.shell-banner-comments
  # - cssho.vscode-svgviewer
  - DavidAnson.vscode-markdownlint
  - EQuimper.react-native-react-redux
  - EditorConfig.EditorConfig
  - Orta.vscode-jest
  - PKief.material-icon-theme
  - christian-kohler.npm-intellisense
  - christian-kohler.path-intellisense
  - dbaeumer.vscode-eslint
  - deerawan.vscode-faker
  - dsznajder.es7-react-js-snippets
  - dunstontc.viml
  - dzannotti.vscode-babel-coloring
  - eamodio.gitlens
  - ericadamski.carbon-now-sh
  - esbenp.prettier-vscode
  - gamunu.vscode-yarn
  - hangxingliu.vscode-nginx-conf-hint
  - heyimfuzz.banner-comments
  - izaxon.todo
  - lamartire.git-indicators
  - lunarlimbo.banner-comments-plus
  - malmaud.tmux
  - mgmcdermott.vscode-language-babel
  - mhutchie.git-graph
  - mikestead.dotenv
  - mrmlnc.vscode-json5
  - ms-azuretools.vscode-docker
  - msjsdiag.vscode-react-native
  - naco-siren.gradle-language
  - naumovs.color-highlight
  - oderwat.indent-rainbow
  - piotrpalarz.vscode-gitignore-generator
  - rebornix.ruby
  - redhat.vscode-yaml
  - softwaredotcom.swdc-vscode
  - spywhere.guides
  - streetsidesoftware.code-spell-checker
  - sumneko.lua
  - waderyan.gitblame
  - wayou.vscode-todo-highlight
  - william-voyek.vscode-nginx
  - wingrunr21.vscode-ruby
  - wix.vscode-import-cost
  - yzhang.markdown-all-in-one
