---

vscode_extensions:
  - christian-kohler.npm-intellisense
  - christian-kohler.path-intellisense
  - davidanson.vscode-markdownlint
  - dbaeumer.vscode-eslint
  - deerawan.vscode-faker
  - dsznajder.es7-react-js-snippets
  - dunstontc.viml
  - eamodio.gitlens
  - editorconfig.editorconfig
  - equimper.react-native-react-redux
  - ericadamski.carbon-now-sh
  - esbenp.prettier-vscode
  - gamunu.vscode-yarn
  - hangxingliu.vscode-nginx-conf-hint
  - heyimfuzz.banner-comments
  - izaxon.todo
  - lamartire.git-indicators
  - lunarlimbo.banner-comments-plus
  - malmaud.tmux
  - mgmcdermott.vscode-language-babel
  - mhutchie.git-graph
  - mikestead.dotenv
  - mrmlnc.vscode-json5
  - ms-azuretools.vscode-docker
  - ms-python.debugpy
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-vscode-remote.remote-containers
  - msjsdiag.vscode-react-native
  - naco-siren.gradle-language
  - naumovs.color-highlight
  - oderwat.indent-rainbow
  - orta.vscode-jest
  - piotrpalarz.vscode-gitignore-generator
  - pkief.material-icon-theme
  - redhat.vscode-yaml
  - shopify.ruby-lsp
  - softwaredotcom.swdc-vscode
  - spywhere.guides
  - streetsidesoftware.code-spell-checker
  - sumneko.lua
  - waderyan.gitblame
  - wayou.vscode-todo-highlight
  - william-voyek.vscode-nginx
  - wix.vscode-import-cost
  - yzhang.markdown-all-in-one
