---

# this taskfile will look for var `apt_packages` to install apt packages.
#   make sure to load it in the playbook

- name: "Add APT source"
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ add_apt_sources }}"
  when: add_apt_sources is defined

- name: "Update apt package repository"
  apt:
    update_cache: true
  become: true

- name: "Upgrade installed packages"
  apt:
    upgrade: "yes"
  become: true

- name: "Install apt packages"
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packages }}"
  ignore_errors: true
  become: true

- name: "Autoremove and Autoclean apt packages"
  apt:
    autoremove: true
    autoclean: true
  become: true
