---

- include_vars: "{{ zshenv.DOTDIR }}/vars/astronvim.yaml"
  tags:
    - astronvim
    - terminal

# remove old Neovim installed plugins
- name: "astronvim: remove old Neovim plugins"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ zshenv.NVIM_CONFIG_DIR_PATH }}"
    - "{{ zshenv.NVIM_PACKER_DIR_PATH }}"
    - "{{ zshenv.NVIM_PACKER_COMPILED_PATH }}"
    - "{{ zshenv.XDG_DATA_HOME }}/nvim/lazy"
    - "{{ zshenv.XDG_DATA_HOME }}/nvim/lazy-lock.json"
    - "{{ zshenv.XDG_CACHE_HOME }}/nvim"
  tags:
    - astronvim
    - terminal

# download latest Astronvim git repo
- name: "astronvim: git clone Astronvim repo"
  git:
    repo: "https://github.com/AstroNvim/AstroNvim"
    dest: "{{ zshenv.NVIM_CONFIG_DIR_PATH }}"
  tags:
    - astronvim
    - terminal

# link astronvim config files
- name: "astronvim: link config file to astronvim"
  file:
    src: "{{ zshenv.DOTDIR }}/tools/astronvim"
    dest: "{{ zshenv.ASTRO_NVIM_CONFIG_DIR_PATH }}"
    state: link
  tags:
    - astronvim
    - terminal

# install astronvim plugins
# install TreeSitter language packs after installing plugins
#   running in async. Requires main thread to be blocked temporarily
- name: "astronvim: install astronvim plugins. Please wait {{ astronvim_install_wait_seconds }} seconds"
  shell:
    cmd: nvim --headless -c 'autocmd User LazyDone quitall' -c 'sleep {{ astronvim_install_wait_seconds }}' -c 'quitall'
  tags:
    - astronvim
    - terminal
