---

# create directories to store code
# link directories to the home folder

- name: "code-directory: Create directory for 'code'"
  file:
    dest: "~/Documents/code"
    state: directory
  tags:
    - code-directory
    - terminal

- name: "code-directory: Create directory for 'temp-git-clone'"
  file:
    dest: "~/Documents/temp-git-clone"
    state: directory
  tags:
    - code-directory
    - terminal

- name: "code-directory: Link directory for 'code' to the home folder"
  file:
    src: "~/Documents/code/"
    dest: "~/code"
    state: link
  tags:
    - code-directory
    - terminal

- name: "code-directory: Link directory for 'temp-git-clone' to the home folder"
  file:
    src: "~/Documents/temp-git-clone/"
    dest: "~/temp-git-clone"
    state: "link"
  tags:
    - code-directory
    - terminal

- name: "code-directory: create orgfiles directory in ~/Documents/ directory"
  file:
    dest: "~/Documents/orgfiles"
    state: directory
  tags:
    - code-directory
    - terminal

- name: "code-directory: create refile for orgmode"
  file:
    dest: "~/Documents/orgfiles/refile.org"
    state: touch
  tags:
    - code-directory
    - terminal

- name: "code-directory: link ~/Document/orgfiles to ~/orgfiles/"
  file:
    src: "~/Documents/orgfiles/"
    dest: "~/orgfiles"
    state: link
  tags:
    - code-directory
    - terminal
