---

- name: "git: Create git directory in {{ ansible_env.GIT_CONFIG_DIR_PATH }}"
  file:
    path: "{{ ansible_env.GIT_CONFIG_DIR_PATH }}"
    state: directory
  tags:
    - git
    - terminal

- name: "git: Add gitconfig file to {{ ansible_env.GIT_CONFIG_PATH }}"
  file:
    src: "{{ ansible_env.DOTDIR }}/tools/git/.gitconfig"
    dest: "{{ ansible_env.GIT_CONFIG_PATH }}"
    state: link
  tags:
    - git
    - terminal

- name: "git: Add gitignore file to {{ ansible_env.GIT_IGNORE_GLOBAL_PATH }}"
  file:
    src: "{{ ansible_env.DOTDIR }}/tools/git/.gitignore_global"
    dest: "{{ ansible_env.GIT_IGNORE_GLOBAL_PATH }}"
    state: link
  tags:
    - git
    - terminal

- name: "git: Add git allowed signers to {{ ansible_env.GIT_ALLOWED_SIGNERS }}"
  file:
    src: "{{ ansible_env.DOTDIR }}/tools/git/allowed_signers"
    dest: "{{ ansible_env.GIT_ALLOWED_SIGNERS }}"
    state: link
  tags:
    - git
    - terminal
