---

# load var file `./vars/go-packages.yaml`
- include_vars: "{{ zshenv.DOTDIR }}/vars/go-packages.yaml"
  tags:
    - go-packages
    - terminal

# install golang packages
- name: "go-packages: Install Golang packages"
  shell:
    cmd: "go install {{ item }}"
  loop: "{{ go_packages }}"
  tags:
    - go-packages
    - terminal
