---

# link Kitty config folder
- name: "kitty: link folder to {{ ansible_env.KITTY_CONFIG_DIRECTORY }}"
  file:
    src: "{{ ansible_env.DOTDIR }}/tools/kitty/"
    dest: "{{ ansible_env.KITTY_CONFIG_DIRECTORY }}"
    state: link
  tags:
    - gui
    - kitty
