---

- name: "lazygit: Create lazygit directory in {{ ansible_env.LAZYGIT_CONFIG_DIR_PATH }}"
  file:
    path: "{{ ansible_env.LAZYGIT_CONFIG_DIR_PATH }}"
    state: directory
  tags:
    - terminal
    - lazygit

- name: "lazygit: Add LazyGit config to {{ ansible_env.LAZYGIT_CONFIG_PATH }}"
  file:
    src: "{{ ansible_env.DOTDIR }}/tools/git/lazygit.yml"
    dest: "{{ ansible_env.LAZYGIT_CONFIG_PATH }}"
    state: link
  tags:
    - terminal
    - lazygit
