---

- name: "lazygit: Create lazygit directory in {{ zshenv.LAZYGIT_CONFIG_DIR_PATH }}"
  file:
    path: "{{ zshenv.LAZYGIT_CONFIG_DIR_PATH }}"
    state: directory
  tags:
    - terminal
    - lazygit

- name: "lazygit: Add LazyGit config to {{ zshenv.LAZYGIT_CONFIG_PATH }}"
  file:
    src: "{{ zshenv.DOTDIR }}/tools/git/lazygit.yml"
    dest: "{{ zshenv.LAZYGIT_CONFIG_PATH }}"
    state: link
  tags:
    - terminal
    - lazygit
