---

- name: "neofetch: Create directory for Neofetch on {{ zshenv.NEOFETCH_CONFIG_DIR_PATH }}"
  file:
    path: "{{ zshenv.NEOFETCH_CONFIG_DIR_PATH }}"
    state: directory
  tags:
    - neofetch
    - terminal

# link Neofetch config file
- name: "neofetch: link Neofetch config file to {{ zshenv.NEOFETCH_CONFIG_PATH }}"
  file:
    src: "{{ zshenv.DOTDIR }}/tools/neofetch/config.conf"
    dest: "{{ zshenv.NEOFETCH_CONFIG_PATH }}"
    state: link
  tags:
    - neofetch
    - terminal
