---

# git clone nerdfounts repo
- name: "nerdfonts: git clone Nerdfonts repo to /tmp/nerdfonts . NOTE: this will take a while"
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: /tmp/nerdfonts
    depth: 1
  tags:
    - gui
    - nerdfonts

- name: "nerdfonts: install Nerdfonts"
  shell:
    cmd: "/tmp/nerdfonts/install.sh"
  tags:
    - gui
    - nerdfonts

- name: "nerdfonts: remove Nerdfonts repo"
  file:
    path: "/tmp/nerdfonts/"
    state: absent
  tags:
    - gui
    - nerdfonts
