---

# setting default configs for raspberry pi
# obtained from:
#   https://loganmarchione.com/2021/07/raspi-configs-mostly-undocumented-non-interactive-mode/
#   https://raspberrypi.stackexchange.com/a/66939
#   https://gist.github.com/damoclark/ab3d700aafa140efb97e510650d9b1be
#   https://github.com/RPi-Distro/raspi-config/blob/master/raspi-config

# ############################################################################################### #
# Localization config
- name: "raspberrypi-configs: Set language to Canadian English"
  shell: raspi-config nonint do_change_locale en_CA.UTF-8
  become: true

- name: "raspberrypi-configs: Specify US keyboard"
  shell: raspi-config nonint do_configure_keyboard us
  become: true

- name: "raspberrypi-configs: Set WiFi country as Canada"
  shell: raspi-config nonint do_wifi_country CA
  become: true

# ############################################################################################### #
# System config
- name: "raspberrypi-configs: Boot to CLI & require login"
  shell: raspi-config nonint do_boot_behaviour B1
  become: true

- name: "raspberrypi-configs: Turn off waiting for network before booting"
  shell: raspi-config nonint do_boot_wait 0
  become: true

# - name: "raspberrypi-configs: Disable splash screen"
#   shell: raspi-config nonint do_boot_splash 1

# ############################################################################################### #
# Display config

# ############################################################################################### #
# Interface config
- name: "raspberrypi-configs: Disable the camera"
  shell: raspi-config nonint do_camera 1
  become: true

- name: "raspberrypi-configs: Disable VNC"
  shell: raspi-config nonint do_vnc 1
  become: true

- name: "raspberrypi-configs: Disable spi bus"
  shell: raspi-config nonint do_spi 1
  become: true

- name: "raspberrypi-configs: Disable the i2c bus"
  shell: raspi-config nonint do_i2c 1
  become: true

- name: "raspberrypi-configs: Disable the RS232 serial bus"
  shell: raspi-config nonint do_serial 1
  become: true

- name: "raspberrypi-configs: Disable onewire on GPIO4"
  shell: raspi-config nonint do_onewire 1
  become: true

- name: "raspberrypi-configs: Disable GPIO server"
  shell: raspi-config nonint do_rgpio 1
  become: true

# ############################################################################################### #
# Performance config


# ############################################################################################### #
# Advanced config

- name: "raspberrypi-configs: Ensures that all of the SD card is available"
  shell: raspi-config nonint do_expand_rootfs
  become: true

# - name: "raspberrypi-configs: Disable predictable network names"
#   shell: raspi-config nonint do_net_names 1
#   become: true

# ############################################################################################### #
# disable ipv6
- name: "raspberrypi-configs: Disable IPv6"
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      # disable ipv6
      # https://gist.github.com/andreibosco/3badaac477446587bcd6751e186df446
      net.ipv6.conf.all.disable_ipv6 = 1
  register: disable_ipv6
  become: true

- name: "raspberrypi-configs: Apply changes for disabling IPv6"
  shell: sysctl -p
  when: disable_ipv6.changed
  become: true
