---

# add apt sources to raspberry pi
- name: "raspberry-pi-apt-sources: add apt source"
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ add_apt_sources }}"
  tags:
    - raspberry-pi-apt-sources
    - terminal
  become: true

# - name: "raspberry-pi-apt-sources: remove apt source"
#   apt_repository:
#     repo: "{{ item }}"
#     state: present
#   loop: "{{ remove_apt_sources }}"
#   tags:
#     - raspberry-pi-apt-sources
#     - terminal
#   become: true
