---

# install spacevim

- name: "spacevim: remove existing vim and SpaceVim directories"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ zshenv.HOME }}/.vim"
    - "{{ zshenv.HOME }}/.SpaceVim"
    - "{{ zshenv.HOME }}/.SpaceVim.d"
    - "{{ zshenv.XDG_CONFIG_HOME }}/vim"
    # - "{{ zshenv.XDG_CONFIG_HOME }}/nvim"
    # - "{{ zshenv.XDG_DATA_HOME }}/nvim"
    # - "{{ zshenv.XDG_STATE_HOME }}/nvim"
    # - "{{ zshenv.XDG_CACHE_HOME }}/nvim"
    - "{{ zshenv.SPACEVIMDIR }}"
    # - "{{ zshenv.XDG_CONFIG_HOME }}/SpaceVim"
  tags:
    - spacevim
    - terminal

- name: "spacevim: install SpaceVim for vim"
  shell: curl -sLf https://spacevim.org/install.sh | bash -s -- --install vim
  tags:
    - spacevim
    - terminal

# - name: "spacevim: install SpaceVim for neovim"
#   shell: curl -sLf https://spacevim.org/install.sh | bash -s -- --install neovim
#   tags:
#     - spacevim
#     - terminal

- name: "spacevim: link config file to ~/.SpaceVim.d/"
  file:
    src: "{{ zshenv.DOTDIR }}/tools/spacevim"
    # dest: "{{ zshenv.HOME }}/.SpaceVim.d"
    dest: "{{ zshenv.SPACEVIMDIR }}"
    state: link
  tags:
    - spacevim
    - terminal
