---

- include_vars: "{{ zshenv.DOTDIR }}/vars/vscode-extensions.yaml"
  tags:
    - vscode-extensions
    - gui

- name: "vscode-extensions: install VScode extensions"
  shell:
    cmd: code --install-extension {{ item }} --force
  loop: "{{ vscode_extensions }}"
  ignore_errors: true
  tags:
    - vscode-extensions
    - gui
