---

- name: "git: create {{ zshenv.XDG_CONFIG_HOME }}/zsh directory"
  file:
    path: "{{ zshenv.XDG_CONFIG_HOME }}/zsh"
    state: directory
  tags:
    - zsh
    - terminal

# link zshrc file
- name: "zsh: link zshrc to {{ zshenv.ZSHRC_PATH }}"
  file:
    src: "{{ zshenv.DOTDIR }}/tools/zsh/.zshrc"
    dest: "{{ zshenv.ZSHRC_PATH }}"
    state: link
    force: true
  tags:
    - zsh
    - terminal

# link zshenv file
- name: "zsh: link zshenv to {{ zshenv.ZSHENV_PATH }}"
  file:
    src: "{{ zshenv.DOTDIR }}/tools/zsh/.zshenv"
    dest: "{{ zshenv.ZSHENV_PATH }}"
    state: link
  tags:
    - zsh
    - terminal

# link zshenv file to $HOME
- name: "zsh: link zshenv to {{ zshenv.HOME }}"
  file:
    src: "{{ zshenv.DOTDIR }}/tools/zsh/.zshenv"
    dest: "{{ zshenv.HOME }}/.zshenv"
    state: link
  tags:
    - zsh
    - terminal

# link zlogin file
- name: "zsh: link zlogin to {{ zshenv.ZLOGIN_PATH }}"
  file:
    src: "{{ zshenv.DOTDIR }}/tools/zsh/.zlogin"
    dest: "{{ zshenv.ZLOGIN_PATH }}"
    state: link
  tags:
    - zsh
    - terminal

- name: "zsh: link powerlevel10k config to {{ zshenv.ZDOTDIR }}/.p10k.zsh"
  file:
    src: "{{ zshenv.ZSH_THEME_DEFAULT }}"
    dest: "{{ zshenv.ZDOTDIR }}/.p10k.zsh"
    state: link
  when: "'powerlevel10k' in lookup('env', 'ZSH_THEME_DEFAULT')"
  tags:
    - zsh
    - terminal

# change default shell to ZSH
- name: "zsh: change default shell to ZSH"
  shell:
    cmd: chsh -s /bin/zsh {{ zshenv.USER }}
  become: true
  ignore_errors: true
  when:
    - zshenv.SHELL != '/bin/zsh'
    - lookup('ansible.builtin.env', 'USER')
  tags:
    - zsh
    - terminal
