---
- include_vars: "npm-packages.yaml"

# used for finding the npm executable installed by nvm
- name: "Store current nodejs version being used by nvm"
  shell:
    cmd: "source {{ zshenv.NVM_DIR }}/nvm.sh && nvm current"
    executable: /bin/bash
  register: node_version
  changed_when: false

- name: "Install global npm packages"
  npm:
    name: "{{ item }}"
    global: true
    # executable: "{{ zshenv.NVM_DIR}}/versions/node/{{ node_version.stdout }}/bin/npm"
  loop: "{{ npm_packages }}"
  environment:
    # obtained from https://truongtx.me/2015/11/02/ansible-install-and-work-with-nodejs-using-nvm#install-npm-tools-with-node-in-nvm
    PATH: "{{ zshenv.NVM_DIR }}/versions/node/{{ node_version.stdout }}/bin:{{ ansible_env.PATH }}"
