---

# copy ssh keys from ansible vault. Stored in group_vars/all.yaml
#
# obtained from:
# - https://github.com/TechDufus/dotfiles/blob/8300c2c/group_vars/all.yml
# - https://github.com/TechDufus/dotfiles/blob/65b150c/roles/ssh/tasks/ssh_keys.yml

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh-test"
    state: directory
    mode: '0700'

- name: "Copy SSH keys"
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh-test/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: 0600
  no_log: true
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_key | default({}) | dict2items }}"
