---

- name: "Create directory for ZSH cache"
  file:
    path: "{{ ansible_env.ZSH_CACHE_DIR }}"
    state: directory
  tags:
    - ohmyzsh
    - terminal

- name: "Remove existing Oh-my-zsh directory"
  file:
    path: "{{ ansible_env.OH_MY_ZSH_DIR_PATH }}"
    state: absent
  tags:
    - ohmyzsh
    - terminal

# install Oh-my-zsh
- name: "Install Oh-my-zsh"
  shell:
    cmd: sh -c "$(curl -o- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  environment:
    ZSH: "{{ ansible_env.OH_MY_ZSH_DIR_PATH }}"
    KEEP_ZSHRC: "yes"
  tags:
    - ohmyzsh
    - terminal
