---

# obtained from
# - https://github.com/TechDufus/dotfiles/blob/ac47994/roles/go/handlers/main.yml#L1-L12

- name: Cleanup go downloaded tar
  ansible.builtin.file:
    path: "/tmp/{{ go_file }}.tar.gz"
    state: absent
  become: true

- name: Remove extracted go directory
  ansible.builtin.file:
    path: /tmp/go
    state: absent
  become: true
