---

- name: "Install Wikiman"
  when: wikiman_latest_release not in installed_wikiman_version.stdout|default('')
  block:
    # query json to get download url
    # obtained from
    # - https://docs.ansible.com/ansible/latest/collections/community/general/docsite/filter_guide_selecting_json_data.html
    - name: "Get download url"
      debug:
        msg: "{{ wikiman_latest_version_json.json | json_query(download_url_query) }}"
      vars:
        download_url_query: "assets[?contains(name, 'rpm')].browser_download_url"
      register: download_url

    # install rpm package using download url
    # NOTE: need to disable gpg check; if installing manually, it will show a comment
    # obtained from
    # - https://stackoverflow.com/a/73797059/3053548
    - name: "Install wikiman"
      dnf:
        name: "{{ download_url.msg[0] }}"
        state: installed
        disable_gpg_check: true
      become: true
