---

# install wikiman. view man pages in terminal. arch wiki too
# - https://github.com/filiparag/wikiman

- name: "Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: distribution_config

# ----------------------------------------------------------------------------------------------- #

- name: "Run install sub-routine"
  when: distribution_config.stat.exists
  block:
    # get wikiman metadata from github release json file

    # get latest wikiman release metadata
    - name: "Download Latest Version JSON"
      ansible.builtin.uri:
        url: https://api.github.com/repos/filiparag/wikiman/releases/latest
      register: wikiman_latest_version_json
      changed_when: false

    # - name: "print version json"
    #   ansible.builtin.debug:
    #     var: wikiman_latest_version_json.json

    - name: "Registering wikiman Latest Release"
      ansible.builtin.set_fact:
        wikiman_latest_release: "{{ wikiman_latest_version_json.json.tag_name }}"

    - name: "Registering wikiman Latest Version"
      ansible.builtin.set_fact:
        wikiman_latest_version: "{{ wikiman_latest_release.stdout | default('') }}"

    - name: Show wikiman_latest_release debug
      ansible.builtin.debug:
        var: wikiman_latest_release

    # get installed wikiman version
    - name: "Check if wikiman is installed"
      shell:
        cmd: command -v wikiman > /dev/null 2>&1
      register: is_wikiman_installed
      ignore_errors: true
      failed_when: false

    - name: "Get installed version"
      # noqa risky-shell-pipe
      shell:
        cmd: |
          wikiman -v | grep -Po "(\d+\.)+\d+" | xargs printf '%s'
      register: installed_wikiman_version
      when: is_wikiman_installed.rc == 0

    - name: "Show installed_wikiman_version"
      ansible.builtin.debug:
        var: installed_wikiman_version.stdout

    # ------------------------------------------------------------------------------------------- #

    - name: "Run Tasks: {{ ansible_distribution }}"
      ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
      when: distribution_config.stat.exists

# ----------------------------------------------------------------------------------------------- #
