#!/bin/sh

# code obtained from https://github.com/Isayso/pi-hole-autoupdate/blob/master/autoupdate
# update for raspbian

# sudo apt update
# sudo apt -yf dist-upgrade
# sudo apt-get -y --purge autoremove
# sudo apt-get autoclean
#pihole -g -up
pihole -up
