---

- include_vars: "{{ zshenv.DOTDIR }}/vars/rust-packages.yaml"

- name: "Install Rust Cargo packages"
  # shell:
  #   cmd: "cargo install {{ item }}"
  community.general.cargo:
    name: "{{ item }}"
  loop: "{{ rust_packages }}"
  ignore_errors: true
