---

# obtained from
# - https://github.com/TechDufus/dotfiles/blob/c476d74/roles/docker/handlers/main.yml

- name: Restart_docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true
  # when: not ansible_host_environment_is_wsl
