---
# - include_vars: "astronvim.yaml"

# remove old Neovim installed plugins
- name: "Remove old Neovim plugins"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    # - "{{ zshenv.NVIM_CONFIG_DIR_PATH }}"
    - "{{ zshenv.NVIM_PACKER_DIR_PATH }}"
    - "{{ zshenv.NVIM_PACKER_COMPILED_PATH }}"
    - "{{ zshenv.XDG_DATA_HOME }}/astronvim-v4/lazy"
    - "{{ zshenv.XDG_DATA_HOME }}/astronvim-v4/lazy-lock.json"
    - "{{ zshenv.XDG_CACHE_HOME }}/astronvim-v4"

# download latest Astronvim git repo
- name: "Git clone Astronvim config"
  git:
    repo: "https://github.com/Clumsy-Coder/astronvim-config-v4.git"
    version: "main"
    dest: "{{ zshenv.XDG_CONFIG_HOME }}/astronvim-v4"
    force: true

# ----------------------------------------------------------------------------------------------- #

# install astronvim plugins
# install TreeSitter language packs after installing plugins
#   running in async. Requires main thread to be blocked temporarily
- name: "Install astronvim plugins"
  command:
    # cmd: nvim --headless -c 'autocmd User LazyDone quitall' -c 'sleep {{ astronvim_install_wait_seconds }}' -c 'quitall'
    cmd: nvim --headless +q
  environment:
    NVIM_APPNAME: astronvim-v4
