tap "buo/cask-upgrade"
tap "cjbassi/gotop"
tap "domt4/autoupdate"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
# Static checker for GitHub Actions workflow files
brew "actionlint"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Fish completion for brew-cask
brew "brew-cask-completion"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Static analysis of C and C++ code
brew "cppcheck"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Banner-like program prints strings as ASCII art
brew "figlet"
# XML-based font configuration API for X Windows
brew "fontconfig"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Alternative to top/htop
brew "glances"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# GNU grep, egrep and fgrep
brew "grep"
# Improved top (interactive process viewer)
brew "htop"
# Display an interface's bandwidth usage
brew "iftop"
# Calculate various network masks, etc. from a given IP address
brew "ipcalc"
# Development kit for the Java programming language
brew "java"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Show markdown documents on text terminals
brew "mdcat"
# Free (GNU) replacement for the Pico text editor
brew "nano"
# Interactive cheatsheet tool for the command-line
brew "navi"
# NCurses Disk Usage
brew "ncdu"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Utility for managing network connections
brew "netcat"
# Port scanning utility for large networks
brew "nmap"
# Development kit for the Java programming language
brew "openjdk"
# Interpreted, interactive, object-oriented programming language
brew "python"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby", link: true
# Install various Ruby versions and implementations
brew "ruby-build"
# Safe, concurrent, practical language
brew "rust"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Yet another network load monitor
brew "slurm"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Version control system designed to be a better CVS
brew "subversion"
# Programmatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Command-line unarchiving tools supporting multiple formats
brew "unar"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# Download YouTube videos from the command-line
brew "youtube-dl"
# UNIX shell (command interpreter)
brew "zsh"
# A terminal based graphical activity monitor inspired by gtop and vtop
brew "cjbassi/gotop/gotop"
# JDK from the Java User Group (JUG)
cask "adoptopenjdk"
# GPU-accelerated terminal emulator
cask "alacritty"
# Tools for building Android applications
cask "android-studio"
# Backup and restore SD cards, USB drives, external HDD, etc
cask "applepi-baker"
# Electronics prototyping platform
cask "arduino"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# E-books management software
cask "calibre"
# Server and cloud storage browser
cask "cyberduck"
# App to build and share containerized applications and microservices
cask "docker"
# terminal fonts that support powerline fonts
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-ibm-plex"
cask "font-source-code-pro"
# Utility to provide quick look previews for files that aren't natively supported
cask "glance"
# Simple and elegant markdown editor
cask "mark-text"
# File system integration
cask "osxfuse"
# Collaboration platform for API development
cask "postman"
# Quick Look plugin for apps and provisioning profile files
cask "provisionql"
# Peer to peer Bitorrent client
cask "qbittorrent"
# QuickLook plug-in that renders source code with syntax highlighting
cask "qlcolorcode"
# QuickLook generator for Markdown files
cask "qlmarkdown"
# A QuickLook plugin that lets you view plain text files without a file extension
cask "qlstephen"
# A QuickLook plugin for CSV files
cask "quicklook-csv"
# Imaging utility to install operating systems to a microSD card
cask "raspberry-pi-imager"
# Standalone app for debugging React Native apps
cask "react-native-debugger"
# Instant messaging application focusing on security
cask "signal"
# Sets a minimum speed for built-in fans
cask "smcfancontrol"
# Music streaming service
cask "spotify"
# Text editor for code, markup and prose
cask "sublime-text"
# Application for inspecting installer packages
cask "suspicious-package"
# Unpacks archive files
cask "the-unarchiver"
# Web browser focusing on security
cask "tor-browser"
# Development environment
cask "vagrant"
# Virtualizer for x86 hardware
cask "virtualbox"
# Extend the functionality of VirtualBox
cask "virtualbox-extension-pack"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Remote desktop application focusing on security
cask "vnc-viewer"
# Network protocol analyzer
cask "wireshark"
# Multi-platform graphical interface for official Nmap Security Scanner
cask "zenmap"
