#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # colorscheme
    # https://spacevim.org/layers/colorscheme/
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme layer.
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit true colors.
    enable_guicolors = true

    # statusline
    # default statusline config. Replaced with vim-airline/vim-airline
    # https://spacevim.org/quick-start-guide/#configuration
    # https://spacevim.org/documentation/#statusline
    # 
    # Disable statusline separator, if you want to use other value, please install nerd fonts.
    statusline_separator = "slant"        # Set the statusline separators of statusline, default is "arrow"
    statusline_iseparator = "bar"         # Set the statusline separators of inactive statusline
    enable_statusline_mode = true         # Display current mode text on statusline

    # bufferline
    # https://spacevim.org/layers/core/statusline/#configuration
    buffer_index_type = 4                 # Set SpaceVim buffer index type
    enable_tabline_filetype_icon = true   # Display file type icon on the tabline.

    # tab
    # https://spacevim.org/documentation/#code-indentation
    default_indent = 2
    expand_tab = true

    # file explorer
    # https://spacevim.org/documentation/#file-tree
    filetree_direction = "left"

####################################################################################################
# Autocomplete                                                                                     #
####################################################################################################

# Enable autocomplete layer
# https://spacevim.org/layers/autocomplete/
[[layers]]
  name = "autocomplete"
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

####################################################################################################
# Core                                                                                             #
####################################################################################################

# SpaceVim core layer provides many default key bindings and features.
# https://spacevim.org/layers/core/
[[layers]]
  name = "core"
  filetree_show_hidden = true       # option for showing hidden file in filetree, disabled by default
  enable_smooth_scrolling = true    # enable/disabled smooth scrolling key bindings, enabled by default.
  filetree_opened_icon = ""
  filetree_closed_icon = ""

####################################################################################################
# Status line                                                                                      #
####################################################################################################

# This layer provides a default statusline for SpaceVim
# https://spacevim.org/layers/core/statusline/
[[layers]]
  name = "core#statusline"
  enable = false              # replaced with vim-airline/vim-airline

####################################################################################################
# Code linting                                                                                     #
####################################################################################################

# Syntax checking automatically within SpaceVim, display error on the sign column and statusline.
# https://spacevim.org/layers/checkers/
[[layers]]
  name = "checkers"
  lint_on_the_fly = true      # Syntax checking on the fly feature, disabled by default.

####################################################################################################
# Fuzzy finder                                                                                     #
####################################################################################################

# This layer provides a heavily customized fzf centric workflow
# https://spacevim.org/layers/fzf/
[[layers]]
  name = "fzf"

####################################################################################################
# Git                                                                                              #
####################################################################################################

# This layer adds extensive support for git
# https://spacevim.org/layers/git/
[[layers]]
  name = "git"

####################################################################################################
# Github                                                                                           #
####################################################################################################

# github 	This layer provides GitHub integration for SpaceVim
# https://spacevim.org/layers/github/
[[layers]]
  name = "github"

####################################################################################################
# Shell                                                                                            #
####################################################################################################

# This layer provides shell support in SpaceVim
# https://spacevim.org/layers/shell/
[[layers]]
  name = "shell"
  default_position = "top"     # top, bottom, left, right, float or full
  default_height = 30

####################################################################################################
# Treesitter                                                                                       #
####################################################################################################

# This layers adds extensive support for treesitter
# https://spacevim.org/layers/treesitter/
[[layers]]
  name = "treesitter"

####################################################################################################
# Language Server Protocol                                                                         #
####################################################################################################

# This layers provides language server protocol for vim and neovim
# https://spacevim.org/layers/language-server-protocol/
[[layers]]
  name = "lsp"

####################################################################################################
# Language support                                                                                 #
####################################################################################################

# Dockerfile language support, including syntax highlighting and code formatting.
# https://spacevim.org/layers/lang/dockerfile/
[[layers]]
  name = "lang#dockerfile"

# Edit html in SpaceVim, with this layer, 
#   this layer provides code completion, syntax checking and code formatting for html.
# https://spacevim.org/layers/lang/html/
[[layers]]
  name = "lang#html"

# This layer provides JavaScript development support for SpaceVim, 
#   including code completion, syntax highlighting and syntax checking
# https://spacevim.org/layers/lang/javascript/
[[layers]]
  name = "lang#javascript"

# This layer is for Lua development, provides autocompletion, 
#   syntax checking, and code format for Lua files.
# https://spacevim.org/layers/lang/lua/
[[layers]]
  name = "lang#lua"

# This layer is for toml development, provides syntax checking, indentation, etc.
# https://spacevim.org/layers/lang/toml/
[[layers]]
  name = "lang#toml"

# This layer is for TypeScript development, including code completion, 
#   Syntax lint, and doc generation.
# https://spacevim.org/layers/lang/typescript/
[[layers]]
  name = "lang#typescript"

# This layer is for writing Vimscript, including code completion, 
#   syntax checking and buffer formatting
# https://spacevim.org/layers/lang/vim/
[[layers]]
  name = "lang#vim"

####################################################################################################
# Plugins                                                                                          #
####################################################################################################

# FUNCTIONAL PLUGINS ----------------------------------------------------------------------------- #


# VISUAL PLUGINS --------------------------------------------------------------------------------- #

# display CSS colors
[[custom_plugins]]
  repo = "lilydjwg/colorizer"
  merged = false

# Colourize brackets, parenthis and curly brackets
[[custom_plugins]]
  repo = "frazrepo/vim-rainbow"
  merged = false

# Vim statusline
[[custom_plugins]]
  repo = "vim-airline/vim-airline"
  merged = false

# Vim statusline themes
[[custom_plugins]]
  repo = "vim-airline/vim-airline-themes"
  merged = false

