---

- include_vars: "astronvim.yaml"

# remove old Neovim installed plugins
- name: "Remove old Neovim plugins"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ zshenv.NVIM_CONFIG_DIR_PATH }}"
    - "{{ zshenv.NVIM_PACKER_DIR_PATH }}"
    - "{{ zshenv.NVIM_PACKER_COMPILED_PATH }}"
    - "{{ zshenv.XDG_DATA_HOME }}/nvim/lazy"
    - "{{ zshenv.XDG_DATA_HOME }}/nvim/lazy-lock.json"
    - "{{ zshenv.XDG_CACHE_HOME }}/nvim"

# download latest Astronvim git repo
- name: "Git clone Astronvim repo"
  git:
    repo: "https://github.com/AstroNvim/AstroNvim"
    version: v3.45.3
    dest: "{{ zshenv.NVIM_CONFIG_DIR_PATH }}"

# link astronvim config files
- name: "Link config file to astronvim"
  file:
    src: "{{ zshenv.DOTDIR }}/tools/astronvim"
    dest: "{{ zshenv.ASTRO_NVIM_CONFIG_DIR_PATH }}"
    state: link

# install astronvim plugins
# install TreeSitter language packs after installing plugins
#   running in async. Requires main thread to be blocked temporarily
- name: "Install astronvim plugins. Please wait {{ astronvim_install_wait_seconds }} seconds"
  command:
    cmd: nvim --headless -c 'autocmd User LazyDone quitall' -c 'sleep {{ astronvim_install_wait_seconds }}' -c 'quitall'
