---

- include_vars: "{{ zshenv.DOTDIR }}/vars/luarocks-packages.yaml"

- name: "luarocks: install luarocks packages"
  shell:
    cmd: "luarocks install {{ item }}"
  loop: "{{ luarocks_packages }}"
  # become: true
