---

# install docker in fedora
# obtained from
# - https://docs.docker.com/engine/install/fedora/
# - https://github.com/abaez/ansible-role-docker/blob/4bc8d42/tasks/os_family/Fedora.yml

- name: "Remove old docker installation"
  dnf:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine
  become: true

- name: "Install package 'dnf-plugin-core'"
  dnf:
    update_cache: true
    name: "dnf-plugins-core"
    state: present
  become: true

- name: "Install docker repository"
  command:
    cmd: dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo --overwrite
  become: true

- name: "Install docker"
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  become: true

- name: "Enable service"
  ansible.builtin.systemd:
    enabled: true
    name: docker
    state: started
  become: true

# allow using docker without sudo
- name: "Add to group"
  ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ ansible_env['USER'] }}"
  become: true

- name: "Ensure docker data directory exists"
  ansible.builtin.file:
    path: "{{  ansible_user_dir }}/.local/lib/docker"
    state: directory
    mode: "0710"
