---

# install Docker on ubuntu based systems
# These steps are based on the official Docker documentation: https://docs.docker.com/engine/install/ubuntu/#installation-methods
#
# obtained from
# - https://github.com/TechDufus/dotfiles/blob/c476d74/roles/docker/tasks/Ubuntu.yml

- name: "Remove old apt source list and gpg keys"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/apt/sources.list.d/docker.list"
    - "/etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list"
    - "/etc/apt/keyrings/docker.asc"
    - "/etc/apt/keyrings/docker.gpg"
  become: true

- name: "Update APT cache"
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: "Install dependencies"
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
  become: true

- name: "Add Docker’s official GPG key"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  become: true

- name: "Get System Architecture"
  ansible.builtin.command: "dpkg --print-architecture"
  register: dpkg_architecture
  changed_when: false
  failed_when: false
  check_mode: false

- name: "Add Docker’s stable repository"
  ansible.builtin.apt_repository:
    repo: deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    mode: "0644"
  become: true

- name: "Install Docker Engine"
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true

- name: "Enable service"
  ansible.builtin.systemd:
    enabled: true
    name: docker
    state: started
  become: true
  # when: not ansible_host_environment_is_wsl

- name: "Add to group"
  ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ ansible_env['USER'] }}"
  become: true

- name: "Ensure docker data directory exists"
  ansible.builtin.file:
    path: "{{  ansible_user_dir }}/.local/lib/docker"
    state: directory
    mode: "0710"

# - name: "Copy daemon.json"
#   ansible.builtin.template:
#     dest: "/etc/docker/daemon.json"
#     src: "daemon.json"
#     mode: "0644"
#   become: true
#   notify: Restart_docker
