---

# install xdg-ninja
# check
# - https://github.com/b3nj5m1n/xdg-ninja

- name: "Create directory {{ zshenv.XDG_DATA_SRC }}"
  file:
    path: "{{ zshenv.XDG_DATA_SRC }}"
    state: directory

- name: "Clone xdg-ninja git repo to {{ zshenv.XDG_DATA_SRC }}/xdg-ninja/"
  git:
    repo: https://github.com/b3nj5m1n/xdg-ninja
    dest: "{{ zshenv.XDG_DATA_SRC }}/xdg-ninja"
    version: main

- name: "Create directory {{ zshenv.XDG_DATA_BIN }}"
  file:
    path: "{{ zshenv.XDG_DATA_BIN }}"
    state: directory

- name: "Create symbolic link to the binary"
  file:
    src: "{{ zshenv.XDG_DATA_SRC }}/xdg-ninja/xdg-ninja.sh"
    dest: "{{ zshenv.XDG_DATA_BIN }}/xdg-ninja"
    state: link
