---

# create directory for alacritty in ~/.config/
- name: "Create directory for alacritty in {{ zshenv.ALACRITTY_CONFIG_DIR_PATH }}"
  file:
    path: "{{ zshenv.ALACRITTY_CONFIG_DIR_PATH }}"
    state: directory

# link Alacritty config file
- name: "Link config file to {{ zshenv.ALACRITTY_CONFIG_PATH }}"
  file:
    src: "{{ zshenv.DOTDIR }}/tools/alacritty/alacritty.yml"
    dest: "{{ zshenv.ALACRITTY_CONFIG_PATH }}"
    state: link
