---
- hosts: "local"
  vars_files:
    - "../vars/homebrew.yaml"
    - "../vars/mas.yaml"
    - "../vars/macos-docks.yaml"
  roles:
    - role: geerlingguy.mac.homebrew
      tags:
        - brew
        - gui
      when: ansible_distribution == 'MacOSX'
      ignore_errors: true

    - role: geerlingguy.mac.mas
      tags:
        - mas
        - gui
      ignore_errors: true

    - role: geerlingguy.mac.dock
      tags:
        - dock
        - gui
      ignore_errors: true

    - role: alacritty
