---
- hosts: "local"
  vars_files:
    - "../vars/global-vars.yaml"
    - "../vars/homebrew.yaml"
    - "../vars/mas.yaml"
    - "../vars/macos-docks.yaml"
  roles:
    - role: elliotweiser.osx-command-line-tools

    - role: geerlingguy.mac.homebrew
      tags:
        - brew
        - gui
      when: ansible_distribution == 'MacOSX'
      ignore_errors: true

    - role: geerlingguy.mac.mas
      tags:
        - mas
        - gui
      ignore_errors: true

    - role: geerlingguy.mac.dock
      tags:
        - dock
        - gui
      ignore_errors: true

    - role: alacritty

    - role: kitty

    - role: git

    - role: nerdfonts

    - role: neofetch

    - role: vimv

    - role: go

    - role: tmux

    - role: astronvim

    - role: zsh

    - role: ohmyzsh

    - role: pip3

    - role: luarocks

  tasks:
    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/code-directory.yaml"
      tags:
        - code-directory
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/nvm.yaml"
      tags:
        - nvm
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/npm.yaml"
      tags:
        - npm
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/roles/vscode/tasks/install-extensions.yaml"
      tags:
        - vscode-extensions
        - gui

    - include_tasks: "{{ ansible_env.DOTDIR }}/roles/rust/tasks/crates.yaml"
      tags:
        - cargo-packages
        - terminal
