---
- hosts: "local"
  vars_files:
    - "../vars/global-vars.yaml"
    - "../vars/homebrew.yaml"
    - "../vars/mas.yaml"
    - "../vars/macos-docks.yaml"
    - "../vars/npm-packages.yaml"
    - "../vars/go-packages.yaml"
  roles:
    - role: geerlingguy.mac.homebrew
      tags:
        - brew
        - gui
      when: ansible_distribution == 'MacOSX'
      ignore_errors: true

    - role: geerlingguy.mac.mas
      tags:
        - mas
        - gui
      ignore_errors: true

    - role: geerlingguy.mac.dock
      tags:
        - dock
        - gui
      ignore_errors: true

    - role: code-directory

    - role: alacritty

    - role: git

    - role: nerdfonts

    - role: nvm

    - role: npm

    - role: neofetch

    - role: vimv

    - role: go

    - role: tmux

    - role: astronvim

    - role: zsh
