---
- hosts: "local"
  vars_files:
    - "../vars/global-vars.yaml"
    - "../vars/homebrew.yaml"
    - "../vars/mas.yaml"
    - "../vars/macos-docks.yaml"
  roles:
    - role: elliotweiser.osx-command-line-tools

    - role: geerlingguy.mac.homebrew
      tags:
        - brew
        - gui
      when: ansible_distribution == 'MacOSX'
      ignore_errors: true

    - role: geerlingguy.mac.mas
      tags:
        - mas
        - gui
      ignore_errors: true

    - role: geerlingguy.mac.dock
      tags:
        - dock
        - gui
      ignore_errors: true

    - role: pip3

    - role: luarocks

  tasks:
    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/code-directory.yaml"
      tags:
        - code-directory
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/alacritty.yaml"
      tags:
        - alacritty
        - gui

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/kitty.yaml"
      tags:
        - kitty
        - gui

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/git.yaml"
      tags:
        - git
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/lazygit.yaml"
      tags:
        - lazygit
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/nerdfonts.yaml"
      tags:
        - nerdfonts
        - gui

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/nvm.yaml"
      tags:
        - nvm
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/npm.yaml"
      tags:
        - npm
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/neofetch.yaml"
      tags:
        - neofetch
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/vimv.yaml"
      tags:
        - vimv
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/go-packages.yaml"
      tags:
        - go-packages
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/tmux.yaml"
      tags:
        - tmux
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/astronvim.yaml"
      tags:
        - astronvim
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/zsh.yaml"
      tags:
        - zsh
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/ohmyzsh.yaml"
      tags:
        - ohmyzsh
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/roles/vscode/tasks/install-extensions.yaml"
      tags:
        - vscode-extensions
        - gui

    - include_tasks: "{{ ansible_env.DOTDIR }}/roles/rust/tasks/crates.yaml"
      tags:
        - cargo-packages
        - terminal
