---
- hosts: "local"
  vars_files:
    - "../vars/global-vars.yaml"
    - "../vars/debian.yaml"
    - "../vars/flatpak.yaml"

  # roles:

  pre_tasks:
    - name: Load envs
      ansible.builtin.import_tasks:
        ../pre_tasks/load-envs.yaml
      tags:
        - always

  tasks:
    # terminal config

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/code-directory.yaml"
      tags:
        - code-directory
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/apt.yaml"
      tags:
        - apt
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/git.yaml"
      tags:
        - git
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/lazygit.yaml"
      tags:
        - lazygit
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/neofetch.yaml"
      tags:
        - neofetch
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/neovim-source-build.yaml"
      tags:
        - neovim-source-build
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/astronvim.yaml"
      tags:
        - astronvim
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/tmux.yaml"
      tags:
        - tmux
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/nvm.yaml"
      tags:
        - nvm
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/npm.yaml"
      tags:
        - npm
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/go-packages.yaml"
      tags:
        - go-packages
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/pyenv.yaml"
      tags:
        - pyenv
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/rust.yaml"
      tags:
        - rust
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/cargo-packages.yaml"
      tags:
        - cargo-packages
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/pip3.yaml"
      tags:
        - pip3
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/vimv.yaml"
      tags:
        - vimv
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/zsh.yaml"
      tags:
        - zsh
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/ohmyzsh.yaml"
      tags:
        - ohmyzsh
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/ufw.yaml"
      tags:
        - ufw
        - terminal

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/xdg-ninja.yaml"
      tags:
        - xdg-ninja
        - terminal

    # ------------------------------------------------------------------------------------------- #
    # gui configs

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/alacritty.yaml"
      tags:
        - alacritty
        - gui

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/kitty.yaml"
      tags:
        - kitty
        - gui

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/nerdfonts.yaml"
      tags:
        - nerdfonts
        - gui

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/flatpak.yaml"
      tags:
        - flatpak
        - gui

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/prusa-slicer.yaml"
      tags:
        - prusa
        - gui

    - include_tasks: "{{ zshenv.DOTDIR }}/tasks/postman.yaml"
      tags:
        - postman
        - gui
