---
- hosts: "local"
  # vars_files:
  #   - "../vars/global-vars.yaml"

  # roles:

  tasks:
    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/raspberry-pi-configs.yaml"
      tags:
        - raspberry-pi-configs
        - terminal
