---
- hosts: "local"
  vars_files:
    - "../vars/global-vars.yaml"
    - "{{ ansible_env.DOTDIR }}/vars/raspberry-pi.yaml"

  # roles:

  tasks:
    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/raspberry-pi-configs.yaml"
      tags:
        - raspberry-pi-configs
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/raspberry-pi-apt-sources.yaml"
      tags:
        - raspberry-pi-apt-sources
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/raspberry-pi-apt.yaml"
      tags:
        - raspberry-pi-apt
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/raspberry-pi-unattended-upgrades.yaml"
      tags:
        - raspberry-pi-unattended-upgrades
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/git.yaml"
      tags:
        - git
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/neofetch.yaml"
      tags:
        - neofetch
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/zsh.yaml"
      tags:
        - zsh
        - terminal
