---
- hosts: "local"
  vars_files:
    - "../vars/global-vars.yaml"
    - "{{ ansible_env.DOTDIR }}/vars/raspberry-pi.yaml"

  # roles:

  tasks:
    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/raspberry-pi-configs.yaml"
      tags:
        - raspberry-pi-configs
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/raspberry-pi-apt-sources.yaml"
      tags:
        - raspberry-pi-apt-sources
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/raspberry-pi-apt.yaml"
      tags:
        - raspberry-pi-apt
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/raspberry-pi-unattended-upgrades.yaml"
      tags:
        - raspberry-pi-unattended-upgrades
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/git.yaml"
      tags:
        - git
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/neofetch.yaml"
      tags:
        - neofetch
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/zsh.yaml"
      tags:
        - zsh
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/ohmyzsh.yaml"
      tags:
        - ohmyzsh
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/nvm.yaml"
      tags:
        - nvm
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/npm.yaml"
      tags:
        - npm
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/spacevim.yaml"
      tags:
        - spacevim
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/neovim-source-build.yaml"
      tags:
        - neovim-source-build
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/pihole.yaml"
      tags:
        - pihole
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/unbound.yaml"
      tags:
        - unbound
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/raspberry-pi-ufw-pihole.yaml"
      tags:
        - pihole-ufw
        - terminal

    - include_tasks: "{{ ansible_env.DOTDIR }}/tasks/pihole-cron.yaml"
      tags:
        - pihole-cron
        - terminal
