---

# build and install neovim
# obtained from
# building and installing:
# https://github.com/neovim/neovim/wiki/Installing-Neovim#install-from-source
# https://github.com/neovim/neovim/wiki/Building-Neovim#quick-start
#
# uninstalling:
# https://github.com/neovim/neovim/wiki/Installing-Neovim#uninstall

# obtained from
# https://github.com/neovim/neovim/wiki/Building-Neovim#ubuntu--debian
- name: "Install build dependencies for debian/ubuntu"
  apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop:
    - ninja-build
    - gettext
    - cmake
    - unzip
    - curl
  when:
    ansible_os_family == "Debian"
  become: true

# obtained from
# https://github.com/neovim/neovim/wiki/Building-Neovim#macos
- name: "Install build dependencies for macOS"
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - ninja
    - gettext
    - cmake
    - curl
  when:
    ansible_os_family == "Darwin"

- name: "Remove currently installed Neovim (built from source)"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/nvim
    - /usr/local/share/nvim
  become: true

- name: "Clone Neovim repo on the stable branch"
  # shell: git clone --depth 1 --branch stable https://github.com/neovim/neovim /tmp/neovim
  git:
    repo: https://github.com/neovim/neovim
    dest: /tmp/neovim
    depth: 1
    version: stable

- name: "Build neovim release"
  command:
    cmd: make CMAKE_BUILD_TYPE=Release
    chdir: /tmp/neovim

- name: "Make install neovim"
  command:
    cmd: make install
    chdir: /tmp/neovim
  become: true

- name: "Removing neovim repo"
  file:
    path: "/tmp/neovim"
    state: absent

# - name: remove init.vim file. Replaced with init.lua
#   shell: rm -rfv ~/.config/nvim/init.vim
#   tags:
#     - neovim-source-build
#     - terminal
