---

- name: "Run Task: pihole.yaml"
  ansible.builtin.include_tasks: "pihole.yaml"

- name: "Run Tasks: unbound.yaml"
  ansible.builtin.include_tasks: "unbound.yaml"

- name: "Run Task: cron.yaml"
  ansible.builtin.include_tasks: "cron.yaml"

- name: "Set var for UFW"
  ansible.builtin.set_fact:
    ufw:
      - port_number: 80
        comment: "Pi-Hole Admin WebPortal"
      - port_number: 53
        comment: "Pi-Hole DNS"

- name: "Run Role: UFW"
  ansible.builtin.include_role:
    name: ufw
