---

# install pihole

- name: "Create directory /etc/pihole"
  file:
    dest: "/etc/pihole"
    state: directory
    owner: pihole
    group: pihole
  become: true

- name: "Link pihole setupVars to /etc/pihole/setupVars.conf"
  copy:
    src: "{{ zshenv.DOTDIR }}/tools/pihole/setupVars.conf"
    dest: "/etc/pihole/setupVars.conf"
    owner: pihole
    group: pihole
  become: true

- name: "Link pihole adlists to /etc/pihole/adlists.conf"
  copy:
    src: "{{ zshenv.DOTDIR }}/tools/pihole/adlists.conf"
    dest: "/etc/pihole/adlists.conf"
    owner: pihole
    group: pihole
  become: true

- name: "Install pihole"
  shell: |
    curl  -sSL \
          --max-time 10 \
          --retry 5 \
          --retry-delay 10 \
          --retry-max-time 40 \
          https://install.pi-hole.net | bash /dev/stdin --unattended
  become: true
