---

# install unbound

- name: "Link unbound config file"
  file:
    src: "{{ zshenv.DOTDIR }}/tools/unbound/pi-hole.conf"
    dest: "/etc/unbound/unbound.conf.d/pi-hole.conf"
  become: true

- name: "Install 'unbound' and 'dns-root-data' via apt"
  apt:
    update_cache: true
    name: "{{ state }}"
    state: present
  loop:
    - unbound
    - dns-root-data
  become: true
  when:
    ansible_os_family == "Debian"

- name: "Restart unbound DNS"
  service:
    name: unbound
    state: restarted
  become: true
